const characters =
    [
        {
            name : "Obi-Wan Kenobi",
            alliance : "Jedi",
            planet : "Coruscant",
            species : "Human",
            occupation : "Jedi Master",
        },
        {
            name : "Anakin Skywalker",
            alliance : "Jedi",
            planet : "Tatooine",
            species : "Human",
            occupation : "Jedi Knight",
        },
        {
            name : "R2-D2",
            alliance : "Republic",
            planet : "Naboo",
            species : "Astromech Droid",
            occupation : "Astromech Droid",
        },
        {
            name : "Captain Rex",
            alliance : "Republic",
            planet : "Kamino",
            species : "Human (Clone)",
            occupation : "Clone Captain",
        },
        {
            name : "Count Dooku",
            alliance : "Sith",
            planet : "Serenno",
            species : "Human",
            occupation : "Sith Lord",
        },
        {
            name : "General Grievous",
            alliance : "Separatists",
            planet : "Kalee",
            species : "Kalee Cyborg",
            occupation : "Separatist General",
        },
        {
            name : "Darth Maul",
            alliance : "Sith",
            planet : "Dathomir",
            species : "Zabrak",
            occupation : "Sith Lord",
        },
        /*========================*/
        {
            name : "Padme Amidala",
            alliance : "Republic",
            planet : "Naboo",
            species : "Human",
            occupation : "Galactic Senator",
        },
        {
            name : "Cad Bane",
            alliance : "Hutt Clan",
            planet : "Duro",
            species : "Duros",
            occupation : "Bounty Hunter",
        },
        {
            name : "Jar Jar Binks",
            alliance : "Republic",
            planet : "Naboo",
            species : "Gungan",
            occupation : "Galactic Representative",
        },
        {
            name : "C-3PO",
            alliance : "Republic",
            planet : "Tatooine",
            species : "Protocol Droid",
            occupation : "Protocol Droid",
        },
        {
            name : "Commander Cody",
            alliance : "Republic",
            planet : "Kamino",
            species : "Human (Clone)",
            occupation : "Clone Commander",
        },
        {
            name : "Boba Fett",
            alliance : "Krayt's Claw",
            planet : "Kamino",
            species : "Human (Clone)",
            occupation : "Bounty Hunter",
        },
        {
            name : "Jango Fett",
            alliance : "Mandalorians",
            planet : "Concord Dawn",
            species : "Human",
            occupation : "Bounty Hunter",
        },
        {
            name : "Kit Fisto",
            alliance : "Jedi",
            planet : "Glee Anselm",
            species : "Nautolan",
            occupation : "Jedi Master",
        },
        {
            name : "Fives",
            alliance : "Republic",
            planet : "Kamino",
            species : "Human (Clone)",
            occupation : "ARC Trooper",
        },
        {
            name : "Saw Gerrera",
            alliance : "Ondern Rebels",
            planet : "Onderon",
            species : "Human",
            occupation : "Freedom Fighter",
        },
        {
            name : "Commander Gree",
            alliance : "Republic",
            planet : "Kamino",
            species : "Human (Clone)",
            occupation : "Clone Commander",
        },
        {
            name : "Bo-Katan Kryze",
            alliance : "House Kryze",
            planet : "Mandalore",
            species : "Human",
            occupation : "Nite Owl Warrior",
        },
        {
            name : "Satine Kryze",
            alliance : "House Kryze",
            planet : "Mandalore",
            species : "Human",
            occupation : "Duchess of Mandalore",
        },
        {
            name : "Hondo Ohnaka",
            alliance : "Ohnaka Gang",
            planet : "Sriluur",
            species : "Weequay",
            occupation : "Pirate",
        },
        {
            name : "Savage Opress",
            alliance : "Sith",
            planet : "Dathomir",
            species : "Zabrak",
            occupation : "Sith Acolyte",
        },
        {
            name : "Poggle the Lesser",
            alliance : "Confederacy of Independent Systems",
            planet : "Geonosis",
            species : "Geonosian",
            occupation : "Archduke of Geonosis",
        },
        {
            name : "Goldie",
            alliance : "Separatists",
            planet : "Nubia",
            species : "Astromech Droid",
            occupation : "Separatist Spy",
        },
        {
            name : "Gar Saxon",
            alliance : "House Vizsla",
            planet : "Mandalore",
            species : "Human",
            occupation : "Governor of Mandalore",
        },
        {
            name : "Cham Syndulla",
            alliance : "Republic",
            planet : "Ryloth",
            species : "Twi'lek",
            occupation : "Freedom Fighter",
        },
        {
            name : "Mother Talzin",
            alliance : "Nightsisters",
            planet : "Dathomir",
            species : "Zabrak",
            occupation : "Nightsisters Clan Mother",
        },
        {
            name : "Ahsoka Tano",
            alliance : "Jedi",
            planet : "Shili",
            species : "Togruta",
            occupation : "Jedi Padawan",
        },
        {
            name : "Asajj Ventress",
            alliance : "Sith",
            planet : "Dathomir",
            species : "Zabrak",
            occupation : "Sith Acolyte",
        },
        {
            name : "Pre Vizsla",
            alliance : "Death Watch",
            planet : "Mandalore",
            species : "Human",
            occupation : "Leader of Death Watch",
        },
        {
            name : "Mace Windu",
            alliance : "Jedi",
            planet : "Haruun Kal",
            species : "Human",
            occupation : "Jedi Master",
        },
        {
            name : "Yoda",
            alliance : "Jedi",
            planet : "Unknown",
            species : "Unknown",
            occupation : "Jedi Grand Master",
        },
        {
            name : "Wullf Yularen",
            alliance : "Republic",
            planet : "Coruscant",
            species : "Human",
            occupation : "Republic Admiral",
        },
    ];

export default characters;

/*
{
    name : "",
    alliance : "",
    planet : "",
    species : "",
    occupation : "",
},

*/